name: Run API tests
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Newman and htmlextra
        run: npm install -g newman newman-reporter-htmlextra
      - name: Run tests
        run: newman run FakeRestApi.collection.json -x --reporters=cli,htmlextra --reporter-htmlextra-export ./results/output.html
      
      - name: Upload Tests Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: ./results/output.html
          if-no-files-found: ignore
          retention-days: 2

      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./results/