name: Run API tests
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Install Newman and htmlextra
        run: npm install -g newman newman-reporter-htmlextra
      - name: Run tests
        run: newman run FakeRestApi.collection.json -r htmlextra --reporter-htmlextra-export output.html
